#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DATABASE_TEST_USER WITH PASSWORD '$DATABASE_TEST_PASSWORD';
	CREATE DATABASE $DATABASE_TEST_DB;
	GRANT ALL ON DATABASE $DATABASE_TEST_DB TO $DATABASE_TEST_USER;
	ALTER DATABASE $DATABASE_TEST_DB OWNER TO $DATABASE_TEST_USER;
	GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC TO $DATABASE_TEST_USER;
EOSQL
